"""A small long-only backtest engine with realistic accounting.

Deliberately narrow: signals are generated by one of a few named strategies,
positions are all-in / all-out, and fills happen on the **next** bar's open to
avoid look-ahead bias. Commission and slippage are charged on both sides.

This is not a replacement for a full backtesting framework — it exists so the
site can show a defensible equity curve and risk stats, and so the AI analysis
endpoint has real numbers to reason about rather than invented ones.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import pandas as pd

TRADING_DAYS = 252


@dataclass
class BacktestConfig:
    strategy: str = "sma_cross"
    fast: int = 20
    slow: int = 50
    rsi_period: int = 14
    rsi_oversold: float = 30.0
    rsi_overbought: float = 70.0
    initial_capital: float = 100_000.0
    commission_bps: float = 5.0  # 0.05% per side
    slippage_bps: float = 2.0  # 0.02% per side


@dataclass
class Trade:
    entry_time: int
    entry_price: float
    shares: float
    exit_time: int | None = None
    exit_price: float | None = None
    pnl: float | None = None
    return_pct: float | None = None


@dataclass
class BacktestResult:
    equity_curve: list[dict] = field(default_factory=list)
    trades: list[dict] = field(default_factory=list)
    stats: dict = field(default_factory=dict)


def _signals(df: pd.DataFrame, cfg: BacktestConfig) -> pd.Series:
    """Return a boolean 'want to be long' series, indexed like df."""
    close = df["Close"]

    if cfg.strategy == "sma_cross":
        fast = close.rolling(cfg.fast).mean()
        slow = close.rolling(cfg.slow).mean()
        return (fast > slow).where(slow.notna(), False)

    if cfg.strategy == "ema_cross":
        fast = close.ewm(span=cfg.fast, adjust=False).mean()
        slow = close.ewm(span=cfg.slow, adjust=False).mean()
        warm = max(cfg.fast, cfg.slow)
        sig = fast > slow
        sig.iloc[:warm] = False
        return sig

    if cfg.strategy == "rsi_reversion":
        delta = close.diff()
        gain = delta.clip(lower=0).ewm(alpha=1 / cfg.rsi_period, adjust=False).mean()
        loss = (-delta.clip(upper=0)).ewm(alpha=1 / cfg.rsi_period, adjust=False).mean()
        rs = gain / loss.replace(0, np.nan)
        rsi = (100 - 100 / (1 + rs)).where(loss != 0, 100.0)

        # Stateful: enter below oversold, hold until above overbought.
        want = pd.Series(False, index=close.index)
        holding = False
        for i, value in enumerate(rsi):
            if np.isnan(value):
                want.iloc[i] = False
                continue
            if not holding and value < cfg.rsi_oversold:
                holding = True
            elif holding and value > cfg.rsi_overbought:
                holding = False
            want.iloc[i] = holding
        return want

    if cfg.strategy == "buy_and_hold":
        return pd.Series(True, index=close.index)

    raise ValueError(
        f"unknown strategy {cfg.strategy!r}; available: "
        "sma_cross, ema_cross, rsi_reversion, buy_and_hold"
    )


def run(df: pd.DataFrame, cfg: BacktestConfig) -> BacktestResult:
    if len(df) < 30:
        raise ValueError("need at least 30 bars to backtest")

    want_long = _signals(df, cfg)
    cost_rate = (cfg.commission_bps + cfg.slippage_bps) / 10_000.0

    cash = cfg.initial_capital
    shares = 0.0
    open_trade: Trade | None = None
    trades: list[Trade] = []
    equity_curve: list[dict] = []

    opens = df["Open"].to_numpy(dtype=float)
    closes = df["Close"].to_numpy(dtype=float)
    times = [int(pd.Timestamp(ts).timestamp()) for ts in df.index]
    desired = want_long.to_numpy(dtype=bool)

    for i in range(len(df)):
        # Act on the PREVIOUS bar's signal, filled at THIS bar's open.
        # Bar 0 has no prior signal, so no trade can happen there.
        if i > 0:
            target_long = bool(desired[i - 1])
            # float() rather than the raw numpy scalar: np.float64 propagates
            # through every derived figure and then fails JSON serialisation.
            fill = float(opens[i])

            if target_long and shares == 0.0:
                budget = cash / (1 + cost_rate)
                shares = budget / fill
                cost = shares * fill * cost_rate
                cash -= shares * fill + cost
                open_trade = Trade(entry_time=times[i], entry_price=fill, shares=shares)

            elif not target_long and shares > 0.0:
                proceeds = shares * fill
                cost = proceeds * cost_rate
                cash += proceeds - cost
                if open_trade:
                    open_trade.exit_time = times[i]
                    open_trade.exit_price = fill
                    gross_entry = open_trade.shares * open_trade.entry_price
                    open_trade.pnl = round(proceeds - cost - gross_entry, 2)
                    open_trade.return_pct = round(
                        (open_trade.pnl / gross_entry * 100) if gross_entry else 0.0, 3
                    )
                    trades.append(open_trade)
                    open_trade = None
                shares = 0.0

        equity_curve.append(
            {"time": times[i], "value": round(cash + shares * float(closes[i]), 2)}
        )

    # Mark any still-open position to the final close so stats include it.
    if shares > 0.0 and open_trade is not None:
        final = float(closes[-1])
        proceeds = shares * final
        cost = proceeds * cost_rate
        gross_entry = open_trade.shares * open_trade.entry_price
        open_trade.exit_time = times[-1]
        open_trade.exit_price = round(final, 4)
        open_trade.pnl = round(proceeds - cost - gross_entry, 2)
        open_trade.return_pct = round((open_trade.pnl / gross_entry * 100) if gross_entry else 0.0, 3)
        trades.append(open_trade)

    return BacktestResult(
        equity_curve=equity_curve,
        trades=[_trade_dict(t) for t in trades],
        stats=_stats(equity_curve, trades, df, cfg),
    )


def _trade_dict(t: Trade) -> dict:
    return {
        "entry_time": t.entry_time,
        "exit_time": t.exit_time,
        "entry_price": round(t.entry_price, 4),
        "exit_price": round(t.exit_price, 4) if t.exit_price is not None else None,
        "shares": round(t.shares, 6),
        "pnl": t.pnl,
        "return_pct": t.return_pct,
    }


def _stats(
    equity_curve: list[dict], trades: list[Trade], df: pd.DataFrame, cfg: BacktestConfig
) -> dict:
    equity = pd.Series([p["value"] for p in equity_curve], dtype=float)
    returns = equity.pct_change().dropna()

    total_return = (equity.iloc[-1] / cfg.initial_capital - 1) * 100

    span_days = max((df.index[-1] - df.index[0]).days, 1)
    years = span_days / 365.25
    cagr = ((equity.iloc[-1] / cfg.initial_capital) ** (1 / years) - 1) * 100 if years > 0 else 0.0

    vol = returns.std(ddof=0) * np.sqrt(TRADING_DAYS) if len(returns) > 1 else 0.0
    mean_ann = returns.mean() * TRADING_DAYS if len(returns) else 0.0
    sharpe = (mean_ann / vol) if vol else 0.0

    downside = returns[returns < 0]
    downside_vol = downside.std(ddof=0) * np.sqrt(TRADING_DAYS) if len(downside) > 1 else 0.0
    sortino = (mean_ann / downside_vol) if downside_vol else 0.0

    running_max = equity.cummax()
    drawdown = (equity / running_max - 1) * 100
    max_dd = float(drawdown.min()) if len(drawdown) else 0.0

    closed = [t for t in trades if t.pnl is not None]
    wins = [t for t in closed if t.pnl > 0]
    losses = [t for t in closed if t.pnl <= 0]
    gross_win = float(sum(t.pnl for t in wins))
    gross_loss = abs(float(sum(t.pnl for t in losses)))

    # Benchmark: buy the first bar's open, hold to the last close, same costs.
    cost_rate = (cfg.commission_bps + cfg.slippage_bps) / 10_000.0
    bh_shares = (cfg.initial_capital / (1 + cost_rate)) / float(df["Open"].iloc[0])
    bh_final = bh_shares * float(df["Close"].iloc[-1]) * (1 - cost_rate)
    bh_return = (bh_final / cfg.initial_capital - 1) * 100

    return {
        "initial_capital": cfg.initial_capital,
        "final_equity": round(float(equity.iloc[-1]), 2),
        "total_return_pct": round(float(total_return), 3),
        "cagr_pct": round(float(cagr), 3),
        "annual_volatility_pct": round(float(vol * 100), 3),
        "sharpe": round(float(sharpe), 3),
        "sortino": round(float(sortino), 3),
        "max_drawdown_pct": round(max_dd, 3),
        "trade_count": len(closed),
        "win_rate_pct": round(len(wins) / len(closed) * 100, 2) if closed else 0.0,
        "profit_factor": round(gross_win / gross_loss, 3) if gross_loss else None,
        "avg_win": round(gross_win / len(wins), 2) if wins else 0.0,
        "avg_loss": round(-gross_loss / len(losses), 2) if losses else 0.0,
        "buy_hold_return_pct": round(float(bh_return), 3),
        "excess_vs_buy_hold_pct": round(float(total_return - bh_return), 3),
        "bars": len(df),
    }
